services:
  - type: web
    name: pdf-extractor-pro
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 2 -b 0.0.0.0:$PORT --timeout 300 wsgi:app"
    envVars:
      - key: FLASK_DEBUG
        value: "False"
      - key: GEMINI_API_KEY
        value: AIzaSyDLumkxN_6uKWwqJKs5QwOT8jP9sGCW0hQ
    healthCheckPath: /health
